packages:
  - apps/*
  - services/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - core-js
  - core-js-pure
  - msgpackr-extract
  - postman-code-generators
  - prisma
  - unrs-resolver
